In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from matplotlib import pyplot as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
def read_data(D):
    X = []
    y = []
    for elem in D:
        X.append(list(elem[0]))
        y.append(elem[1])
    return np.array(X), np.array(y)

def read_2d_df(D):
    data = [[t[0][0], t[0][1], t[1]] for t in D]
    df = pd.DataFrame(data)
    return df.iloc[:,0:-1].values, df.iloc[:,-1].values, df

## Frage 1

In [4]:
from sklearn.tree import DecisionTreeClassifier

D_train={((37.5,2),1),((36,1),0),((39,1),1),((37.5,1),0),((39,0),1),((37.5,0),0),((37.5,1),0),((36,2),1)}
D_test={((36,0),0),((37.5,1),0),((39,1),1),((39,2),0)}
X_train, y_train, df_train = read_2d_df(D_train)
X_test, y_test, df_test = read_2d_df(D_test)

tree = DecisionTreeClassifier().fit(X_train, y_train)
y_pred = tree.predict(X_test)
print(y_pred)

[1 0 1 0]


In [18]:
from sklearn import metrics
print(y_pred)
print(y_test)
print(metrics.confusion_matrix(y_test, y_pred))

cm = metrics.confusion_matrix(y_test, y_pred)
confusion_matrix = [[cm[1][1], cm[0][1]], [cm[1][0], cm[0][0]]]
print(np.array(confusion_matrix))

[1 0 1 0]
[1 0 0 0]
[[2 1]
 [0 1]]
[[1 1]
 [0 2]]


## Frage 2

In [25]:
from sklearn.ensemble import RandomForestClassifier

D_train={((37.5,2),1),((36,1),0),((39,1),1),((37.5,1),0),((39,0),1),((37.5,0),0),((37.5,1),0),((36,2),1)}
D_test={((36,0),0),((37.5,1),0),((39,1),1),((39,2),0)}
X_train, y_train, df_train = read_2d_df(D_train)
X_test, y_test, df_test = read_2d_df(D_test)

forest = RandomForestClassifier(n_estimators=100)
forest.fit(X_train, y_train)
y_pred = forest.predict(X_test)
print(y_pred)

[1 0 1 0]


{((36, 1), 0),
 ((36, 2), 1),
 ((37.5, 0), 0),
 ((37.5, 1), 0),
 ((37.5, 2), 1),
 ((39, 0), 1),
 ((39, 1), 1)}

In [23]:
from sklearn import metrics

print("Genauigkeit:", metrics.accuracy_score(y_test, y_pred))
print("F1:", metrics.f1_score(y_test, y_pred))

Genauigkeit: 0.75
F1: 0.6666666666666666


In [24]:
for t in [10, 1000]:
    print("t=",t)
    forest = RandomForestClassifier(n_estimators=t)
    forest.fit(X_train, y_train)
    y_pred = forest.predict(X_test)
    print(y_pred)
    print("Genauigkeit:", metrics.accuracy_score(y_test, y_pred))
    print("F1:", metrics.f1_score(y_test, y_pred))
    print()

t= 10
[1 0 1 0]
Genauigkeit: 0.75
F1: 0.6666666666666666

t= 1000
[1 0 1 0]
Genauigkeit: 0.75
F1: 0.6666666666666666

