In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [24]:
from sklearn.cluster import KMeans

E = [(8.5,16),(12.4,26.8),(9.3,21),(11.5,17),(17.5,25),(13,22.6),(4,16.5)]
X = np.array(E)

knn2 = KMeans(n_clusters=2)
knn2.fit_predict(X)

/opt/conda/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 1, 0, 0, 1, 1, 0], dtype=int32)

In [25]:
knn2.cluster_centers_

array([[ 8.325, 17.625],
       [14.3  , 24.8  ]])

In [26]:
knn2.inertia_

69.875

In [27]:
knn3 = KMeans(n_clusters=3)
knn3.fit_predict(X)

/opt/conda/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


array([0, 1, 0, 0, 1, 1, 2], dtype=int32)

In [28]:
np.round(knn3.cluster_centers_,3)

array([[ 9.767, 18.   ],
       [14.3  , 24.8  ],
       [ 4.   , 16.5  ]])

In [29]:
knn3.inertia_

43.24666666666666