In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
def read_data(D):
    X = []
    y = []
    for elem in D:
        X.append(list(elem[0]))
        y.append(elem[1])
    return np.array(X), np.array(y)

def read_2d_df(D):
    data = [[t[0][0], t[0][1], t[1]] for t in D]
    df = pd.DataFrame(data)
    return df.iloc[:,0:-1].values, df.iloc[:,-1].values, df

In [31]:
from sklearn.decomposition import PCA

E=[[-1.222,-1.297,-1.648],[-0.604,-0.208,1.436],[1.247,0.809,-0.414],[1.247,1.826,-0.846],[-0.693,0.301,1.128],[-0.869,-1.006,0.141],[0.894,-0.425,0.203]]
X = np.array(E)

print(X)
pca = PCA(n_components=3)
pca.fit(X)
np.round(pca.components_, 2)


[[-1.222 -1.297 -1.648]
 [-0.604 -0.208  1.436]
 [ 1.247  0.809 -0.414]
 [ 1.247  1.826 -0.846]
 [-0.693  0.301  1.128]
 [-0.869 -1.006  0.141]
 [ 0.894 -0.425  0.203]]


array([[ 0.71,  0.69, -0.14],
       [ 0.01, -0.21, -0.98],
       [ 0.71, -0.69,  0.16]])

In [38]:
cov_matrix = np.cov(np.transpose(X))
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("Eigenvalues:", np.round(eigenvalues, 3))
print("Eigenvectors:\n", np.round(eigenvectors, 3))

Eigenvalues: [0.263 2.065 1.171]
Eigenvectors:
 [[-0.706  0.708 -0.012]
 [ 0.69   0.692  0.212]
 [-0.158 -0.142  0.977]]
